name: CI

on: [pull_request, pull_request_target]

env:
  PYTHON_VERSION: "3.12"

jobs:
  lint_format:
    timeout-minutes: 10
    name: "Lint and Format"
    runs-on: ubuntu-latest
    
    steps:
      - name: "Check Out"
        uses: actions/checkout@v4

      - name: "Lint"
        uses: astral-sh/ruff-action@v1
        with:
          args: "check --fix"
          changed-files: "true"

      - name: "Format"
        uses: astral-sh/ruff-action@v1
        with:
          changed-files: "true"
          args: "format"

      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: "${{ env.PYTHON_VERSION }}"

      # - name: "Install uv"
      #   uses: astral-sh/setup-uv@v4

      # - name: "Python format"
      #   run: uvx ruff format --diff . --exclude video

      # - name: "Python lint"
      #   run: uvx ruff check . --exclude video

      # - name: "Python type check"
      #   run: uvx mypy

  typos:
    timeout-minutes: 10
    name: "Code Spell Checker"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@master
        with:
          files: .

  commit:
    timeout-minutes: 10
    name: "Commit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Detect changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV
          fi

      - name: Commit files
        if: env.no_changes == 'false' # 只有在文件有更改时才执行
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"

      - name: Push changes
        if: env.no_changes == 'false' # 只有在文件有更改时才执行
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.head_ref }}
